### ISSUE TITLE
Bug: Patch Failing Docker Image

### ISSUE THREAD

**Issue by renaz6** [xmidt-org/gungnir#145]
The Dockerfile needs to be updated to include this patch:
https://github.com/xmidt-org/tr1d1um/commit/df49bb536fa91ca46fec6384534ddc674406a2b9

## Steps:
- [ ] create missing entrypoint.sh
- [x]  fix linter errors
- [x]  replace deprecated library usage of `Maintainer`

**Comment by denopink** [comment]
blocked since we're missing a `entrypoint.sh` file
